{
 "title": "SonarQube Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "SonarQube Coverage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT analysis_date AS \"time\", project_key, coverage::float FROM sonarqube_results WHERE $__timeFilter(analysis_date) AND project_key = 'shantanu10839179_github-actions-lab' ORDER BY analysis_date ASC;"
    }
   ]
  },
  {
   "title": "SonarQube Bugs, Vulnerabilities, Code Smells",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT analysis_date AS \"time\", bugs::int, vulnerabilities::int, code_smells::int FROM sonarqube_results WHERE $__timeFilter(analysis_date) AND project_key = 'shantanu10839179_github-actions-lab' ORDER BY analysis_date ASC;"
    }
   ]
  },
  {
   "title": "SonarQube Reliability Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT reliability_rating::float FROM sonarqube_results WHERE project_key = 'shantanu10839179_github-actions-lab' ORDER BY analysis_date DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "SonarQube Security Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT security_rating::float FROM sonarqube_results WHERE project_key = 'shantanu10839179_github-actions-lab' ORDER BY analysis_date DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "SonarQube Maintainability Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT maintainability_rating::float FROM sonarqube_results WHERE project_key = 'shantanu10839179_github-actions-lab' ORDER BY analysis_date DESC LIMIT 1;"
    }
   ]
  }
 ]
}